---
name: flutter_sekolahku
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  faker: ^1.3.0
  sqflite: ^2.0.0+3
  fluttertoast: ^8.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.1.4+1
  flutter_launcher_icons: ^0.9.0
flutter_native_splash:
  image: assets/images/sekolah.png
  color: '#ffffff'
flutter_icons:
  image_path: assets/images/sekolah.png
  android: launcher_icon
  ios: true
flutter:
  uses-material-design: true
  assets:
  - assets/images/
